### ISSUE TITLE
Incompatible with GCM/Firebase 11+

### ISSUE THREAD

**Issue by shekibobo** [RadiusNetworks/campaignkit-android#7]
SDK does not work with Google Play Services/Firebase 11+. Can we expect an update any time soon?

```
Caused by: com.radiusnetworks.proximity.geofence.GooglePlayServicesException: Only supported for Google Play Services Library versions 4.2.42 through < 11.0
  at com.radiusnetworks.proximity.geofence.GeofenceServiceManager.checkGeofencingPrerequisites(GeofenceServiceManager.java:279)
  at com.radiusnetworks.proximity.geofence.GeofenceServiceManager.getGeofenceManager(GeofenceServiceManager.java:188)
  at com.radiusnetworks.proximity.ProximityKitManager.enableGeofences(ProximityKitManager.java:381)
  at com.radiusnetworks.campaignkit.CampaignKitManager.enableGeofences(CampaignKitManager.java:771)
```

**Comment by cupakromer** [comment]
This is fixed in the latest [version 0.14.0 release](https://github.com/RadiusNetworks/campaignkit-android/releases/tag/0.14.0).
